### ISSUE TITLE
Java object and database mismatch

### ISSUE THREAD

**Issue by kurdtpage** [OwlNavi/Taskvatar#10]
This is what we have in Android studio (java objects):
![345_java](https://user-images.githubusercontent.com/1308716/44697116-7fdd6200-aace-11e8-84ac-d6b9db62c580.png)
This is what we have on the database side (SQL):
![345_database](https://user-images.githubusercontent.com/1308716/44697127-8966ca00-aace-11e8-94d1-f4ffd3bd5f24.png)
We should consolidate and match them both up so we are seamlessly moving from java objects to sql tables.

**Comment by OwlNavi** [comment]
Closed
